[admin] Don't try to resolve user name if SUDO_USER is set
Fixes #282

OpenShift-created UIDs don't have corresponding user names.  Koschei
would try to eagerly resolve user name, even if SUDO_USER was set.

This change prevents crash in OpenShift with error like:
KeyError: 'getpwuid(): uid not found: 1000550000'