[views] Avoid calling limit() on query twice
limit() is already called by paginate().
Two calls cause the following error:

  InvalidRequestError: Query.order_by() being called on a Query which
  already has LIMIT or OFFSET applied. To modify the row-limited
  results of a Query, call from_self() first.  Otherwise, call
  order_by() before limit() or offset() are applied.