[package-detail] Fix Koji build URL
Currently the URL sets the "match" parameter to an empty string, which
is rejected by Koji:

    An error has occurred in the web interface code. This could be due to a bug or a configuration issue.
    koji.GenericError: No such match type: ''

Fix the URL template by passing "match=exact" instead, which works as
intended.

Signed-off-by: Ondrej Mosnáček <omosnacek@gmail.com>